#=============================================================================
# dark_powered.toml --- dark powered configuration example for SpaceVim
# Copyright (c) 2016-2017 Wang Shidong & Contributors
# Author: Wang Shidong < wsdjeg at 163.com >
# URL: https://spacevim.org
# License: GPLv3
#=============================================================================

# All SpaceVim option below [option] section
[options]
    enable_guicolors = false
    statusline_separator = "nil"
    statusline_inactive_separator = "nil"
    buffer_index_type = 4
    enable_tabline_filetype_icon = true
    enable_statusline_mode = false
    colorscheme = "gruvbox"
    colorscheme_bg = "dark"
    default_indent = 4
    relativenumber = false
    
[[layers]]
    name = "colorscheme"

# Enable autocomplete layer
[[layers]]
    name = "autocomplete"
    auto-completion-return-key-behavior = "complete"
    auto-completion-tab-key-behavior = "smart"

[[layers]]
    name = "ctrlp"

[[layers]]
    name = "shell"
    default_position = "bottom" 
    default_height = 32

[[layers]]
    name = "git"

[[layers]]
    name = "lang#python"
    python_interpreter = "~/.pyenv/shims/python"

[[layers]]
    name = "lang#html"

#[[layers]]
#    name = "lang#javascript"

[[layers]]
    name = "lang#markdown"

[[layers]]
    name = "lang#sh"
